### ISSUE TITLE
Is Clang stable ?

### ISSUE THREAD

**Issue by jeremieca** [pangloss/clang#12]
Hello,

I have two questions :
- Clang is it ready to develop production tools ?
- When will clang push on Clojar ?

**Comment by pangloss** [comment]
No, you shouldn't consider it production ready unless you are willing to dive in and fix or extend clang if you run into any issues. I am not actively using it right now and have no immediate plans to do so, simply because my focus is on other projects. On the other hand, it does work...

**Comment by jeremieca** [comment]
Thanks. :)
