### ISSUE TITLE
clang seems not such a good project name

### ISSUE THREAD

**Issue by rogererens** [pangloss/clang#7]
clang is already being used for compiling c/c++, so your project might find it difficult to be found
http://clang.llvm.org/

**Comment by pangloss** [comment]
Hey, yeah I'm aware of the other project, but I don't think there's any chance of confusion. If you search for "clang clojure" this repo is already occupying spots 2-4, so there doesn't seem to be too much competition for the search term. If the other guys object to us using the name that's different, but for now at least, I really like the name!

**Comment by Gonzih** [comment]
I agree. Really confusing project name. First I saw it I was thinking about some llvm based asm.js magic.

Why not something simple like Angular.cljs or Clojang or something similar?

**Comment by noprompt** [comment]
I'm gonna throw in with the other guys here; it's a confusing name. 

Since I like naming things, how about **Jangular**? It'd be a great, funky name without the attached confusion. :smile_cat:
