### ISSUE TITLE
can't require `clang.js-types`

### ISSUE THREAD

**Issue by xhh** [pangloss/clang#8]
When I require `clang.js-types` in one of my .cljs file, _lein cljsbuild auto_ gives the following warnings:

> WARNING: Use of undeclared Var clang.js-types/INamed at line 28 /Users/xhh/builds/clang/client/clang/js_types.cljs
> WARNING: Symbol INamed is not a protocol at line 28 /Users/xhh/builds/clang/client/clang/js_types.cljs
> WARNING: Use of undeclared Var clang.js-types/INamed at line 28 /Users/xhh/builds/clang/client/clang/js_types.cljs
> WARNING: Use of undeclared Var clang.js-types/-name at line 28 /Users/xhh/builds/clang/client/clang/js_types.cljs

and the web page has the following javascript error

> Uncaught TypeError: Cannot set property 'function' of undefined 

at the line of the generated javascript:
`clang.js_types.INamed["function"] = true;`

BTW, I'm using Clojure 1.5.1

**Comment by pangloss** [comment]
I've been compiling against the head of ClojureScript for the last few
days. Perhaps I've referenced something that isn't in the release version
yet. I'll take a look...
